version: 2
jobs:
  build:
    working_directory: ~/lgbtq-helper-api
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - .node_modules
      - run:
          name: test
          command: |
            mkdir ~/tmp
            TMP=~/tmp/ npm test
